export const timelineData = [
  {
    year: "1936",
    title: "Inherited Giants",
    summary: "tyeste tset set set set ",
    img: "https://i.imgur.com/7Y8uzRc.jpg",
    bottom: "-250px",
    left: "-100px",
  },
  {
    year: "1946",
    title: "asdasd asdasd",
    summary: "tyeste tseasdasdasdt set set set ",
    img: "https://i.imgur.com/Ng5hk9R.jpg",
    bottom: "-250px",
    left: "-100px",
  },
  {
    year: "1946",
    title: "asdasd asdasd",
    summary: "tyeste tseasdasdasdt set set set ",
    img: "https://i.imgur.com/TMcD9om.jpg",
    bottom: "-250px",
    left: "-100px",
  },
  {
    year: "1946",
    title: "asdasd asdasd",
    summary: "tyeste tseasdasdasdt set set set ",
    img: "https://i.imgur.com/rDrSK4i.jpg",
    bottom: "-250px",
    left: "-100px",
  },
  {
    year: "1946",
    title: "asdasd asdasd",
    summary: "tyeste tseasdasdasdt set set set ",
    img: "https://i.imgur.com/cd1QAFq.jpg",
    bottom: "-250px",
    left: "-100px",
  },
  {
    year: "1946",
    title: "asdasd asdasd",
    summary: "tyeste tseasdasdasdt set set set ",
    img: "https://i.imgur.com/Ng5hk9R.jpg",
    bottom: "-250px",
    left: "-100px",
  },
  {
    year: "1946",
    title: "asdasd asdasd",
    summary: "tyeste tseasdasdasdt set set set ",
    img: "https://i.imgur.com/NwfcqQA.jpg",
    bottom: "-250px",
    left: "-100px",
  },
  {
    year: "1946",
    title: "asdasd asdasd",
    summary: "tyeste tseasdasdasdt set set set ",
    img: "https://i.imgur.com/20rrvnp.jpg",
    bottom: "-250px",
    left: "-100px",
  },
  {
    year: "1946",
    title: "asdasd asdasd",
    summary: "tyeste tseasdasdasdt set set set ",
    img: "https://i.imgur.com/jPui7zW.jpg",
    bottom: "-250px",
    left: "-100px",
  },
  {
    year: "1946",
    title: "asdasd asdasd",
    summary: "tyeste tseasdasdasdt set set set ",
    img: "https://i.imgur.com/gclza1K.jpg",
    bottom: "-250px",
    left: "-100px",
  },
];
